export const BANNED = ['NAV', 'expense ratio', 'XIRR', 'AUM', 'folio', 'units', 'alpha', 'beta', 'large-cap', 'mid-cap', 'small-cap', 'equity', 'debt', 'ELSS', 'direct plan', 'regular plan', 'redemption', 'lock-in', 'KYC', 'demat'];

export const SCREEN = {
  welcome: {
    title: 'First Investment mode',
    body: 'Groww has everything a first investor needs. The hard part is knowing what to do next. This mode walks you from "I should start" to "I know what I am doing", in three short steps.',
    cta: 'Show me the path',
  },
  home: {
    title: 'Your first investment',
    steps: [
      { n: 1, name: 'Account', before: { chip: 'Documents needed', body: 'Six things, most on your phone, each with a why.', link: 'See the list' }, after: { chip: 'Verifying', body: 'Submitted. Groww checks within 24 working hours. Use the wait for steps 2 and 3.' } },
      { n: 2, name: 'The basics', before: { chip: '2 minutes', body: 'What a fund is, what risk means, what a fall does. No course.', cta: 'Read the three cards' }, after: { chip: 'Done', body: 'You know what a fund is, what risk means, what a fall does.' } },
      { n: 3, name: 'First money in', before: { chip: '2 minutes', body: 'Decide once what stays untouched and what share of the rest goes in.', cta: 'Plan my first move' }, after: { chip: 'Planned' } },
    ],
    how: { title: 'How this works', lines: ['Groww checks your documents once.', 'Money moves by UPI mandate to the fund house, in your name, never to the app.', 'Stop or take money back any time; a few working days.'] },
    landed: 'Money just landed', run: 'Run the rule', landedLabel: 'Amount that landed', change: 'Change or stop', next: 'Next time money lands, this runs by itself.', runs: 'Runs so far',
    holds: 'What your {invested} now holds', holdsNote: 'A tiny piece of each, in your name, held at the fund house.',
    share: 'Share this', shareTitle: 'My first move', shareWorking: '{sum} working since today', done: 'Done',
  },
  kyc: {
    title: 'What Groww needs, and why',
    ready: '{n} of 6 ready',
    rows: [
      { id: 'pan', name: 'PAN card', why: 'Tax rules require it for any investment account.', where: 'Most people have one. If not, apply on the income tax site; it takes about two days.' },
      { id: 'aadhaar', name: 'Aadhaar, with your own phone linked', why: 'The OTP goes to the phone linked to it.', where: 'If it is linked to a parent’s number, ask them to read out the OTP, or update the number at any Aadhaar centre. Everything else stays on your phone.' },
      { id: 'bank', name: 'A bank account in your name', why: 'Money moves only to and from this account.', where: 'A joint account or a parent’s account will not work. A basic savings account is enough.' },
      { id: 'selfie', name: 'A selfie', why: 'A live check that you are you.', where: 'Taken in the app, in good light.' },
      { id: 'sign', name: 'Your signature on white paper', why: 'The regulator asks for a signature image.', where: 'Sign on plain paper and photograph it.' },
      { id: 'nominee', name: 'A nominee', why: 'Someone who gets the money if something happens to you.', where: 'Any family member’s name and date of birth.' },
    ],
    fno: { name: 'For F&O only: income proof', sub: 'Salary slip, bank statement or tax return', why: 'The regulator requires it. Most students do not have it, which is why F&O shows Activate.', where: 'Not needed for funds or stocks.' },
    cta: 'I have these',
  },
  basics: {
    title: 'The basics',
    cards: [
      { title: 'What a mutual fund is', body: 'Your money joins thousands of other people’s money and buys a slice of many companies at once. One purchase, many companies. A fund house holds it in your name.' },
      { title: 'What risk means', body: 'Prices move every day. Risk is how far they can move against you, and for how long. A broad fund of big companies moves less than one company, and far less than a bet on a date.' },
      { title: 'What happens when markets fall', body: 'It happens most years for a while. A bad year is about a 25% fall: ₹1,000 becomes about ₹750. Broad markets have recovered every time so far; nobody can promise when. Money you need soon should not be here.' },
    ],
    next: 'Next', done: 'Got it',
  },
  rule1: { title: 'How does your money arrive?', shapes: [['regular', 'Regular', 'Same amount, on a date you know'], ['irregular', 'Irregular', 'Different amounts, no fixed date'], ['onetime', 'One-time', 'Came once, not coming again soon']], label: 'Roughly how much came in last time?', err: 'Pick one of the three and enter the amount, more than ₹0.', cta: 'Next' },
  rule2: { title: 'What has to stay untouched each month?', hint: 'Rent, food, money sent home, EMIs. A rough total is enough.', zero: '₹0 means nothing is kept aside. Fine if that is true.', over: 'That is more than the {L} that came in, so nothing is left to invest. You can still go on.', cta: 'Next' },
  rule3: { title: 'How much of what is left becomes an investment?', line: '{share} of the {left} left after your floor.', half: 'Half is the most this plan takes, so half of what is left always stays with you.', cta: 'Next' },
  rule4: { title: 'Decide once', sub: 'Into a broad-market index fund.', crash: 'App crashes mid-way? Money goes by UPI mandate to the fund house, never to the app.', stop: 'Pause or stop the plan any time. Money back takes a few working days.', cap: 'First run: ₹100 only', capNote: 'First run only. After that, the plan runs in full.', cta: 'Set this rule' },
  invest: {
    title: 'Invest',
    one: { title: 'One fund is enough to start', body: 'A broad-market index fund holds a slice of India’s biggest companies. Nothing to pick, nothing to time.', cta: 'Use this in my plan' },
    later: { title: 'Other options, for later', rows: [['Gold', 'Moves differently from companies. Useful after your plan has run a few times.'], ['Small companies', 'Bigger swings both ways. Not a first step.'], ['Government bonds', 'Steadier, slower. Fine for money you need within two years.']] },
  },
  stocks: { title: 'Stocks', card: { title: 'Stocks come second', body: 'Single companies swing more than a broad fund. Most people your age who start here stop within a year. Your first fund is a better first step; stocks stay open.' }, rows: ['HDFC Bank', 'ITC', 'Tata Steel', 'Canara Bank', 'PNB'], note: 'Prototype: live prices not included.' },
  fno: { title: 'F&O', card: { title: 'Read this first', body: 'F&O is a bet on where a price will be by a date. If it goes the other way, the whole amount can go. SEBI found 9 in 10 people who trade F&O lose money, about ₹1,20,000 a year on average (2024). Activation needs income proof.' }, ask: 'Ask before you invest in F&O', activate: 'Activate (income proof needed)', rows: ['NIFTY 22 Sep 23600 Call', 'NIFTY 22 Sep 23500 Call', 'SENSEX 17 Sep 74000 Put', 'SENSEX 17 Sep 75000 Call', 'Crude Oil Mini'], note: 'Prototype: live prices not included.' },
  you: { title: 'You', name: 'Nilay', line: 'Prototype for a case study. Not affiliated with Groww.', mode: 'First Investment mode', modeNote: 'The full layout is out of scope in this prototype.', account: 'Account', accountBefore: 'Documents needed', accountAfter: 'Submitted, verifying', reset: 'Reset demo' },
  tabs: [['home', 'Home'], ['invest', 'Invest'], ['stocks', 'Stocks'], ['fno', 'F&O'], ['you', 'You']],
};

export const GUIDE = {
  name: 'Ask before you invest',
  fallback: 'I only know this app. Try one of these:',
  more: 'More topics',
  placeholder: 'Type a question',
  opening: {
    '/welcome': 'You’re in. Ask me what happens next.',
    '/': 'Three steps. Ask me about any of them.',
    '/kyc': 'Six things. Ask me about any row.',
    '/basics': 'Three cards. Ask me if any of them is unclear.',
    '/rule/1': 'Pick the shape that fits most months.',
    '/rule/2': 'This is the number the plan never touches.',
    '/rule/3': 'Slide it. The rupee figure updates as you go.',
    '/rule/4': 'Last step. Ask me the scary questions.',
    '/invest': 'One fund is enough to start. Ask me why.',
    '/stocks': 'Stocks stay open. Ask me why they come second.',
    '/fno': 'Read the red card first, then ask me anything.',
    '/you': 'Prototype settings. Ask me what resets.',
  },
  topics: [
    { id: 'start', name: 'Start here', qa: [
      { id: 'start1', q: 'How do I start?', a: 'Three steps: documents once, read three cards, decide your first move. Home shows where you are.', t: ['start', 'begin', 'first', 'how'] },
      { id: 'start2', q: 'What documents do I need?', a: 'PAN, Aadhaar with your phone linked, a bank account in your name, a selfie, a signature photo and a nominee. The list on Home explains each.', t: ['documents', 'document', 'need', 'pan', 'aadhaar', 'list'] },
      { id: 'start3', q: 'How long does it take?', a: 'Documents take about 10 minutes if you have them. Groww then checks them within 24 working hours.', t: ['long', 'time', 'hours', 'wait', 'days'] },
      { id: 'start4', q: 'The OTP went to my dad’s phone.', a: 'Aadhaar sends it to the number linked at enrolment. Ask them to read it out, or update the number at any Aadhaar centre.', t: ['otp', 'dad', 'father', 'parent', 'phone', 'number'] },
      { id: 'start5', q: 'Why does it say verifying?', a: 'A person or a system checks your documents. Nothing moves until that is done. Use the wait for the basics and your plan.', t: ['verifying', 'verify', 'verified', 'checking', 'pending'] },
      { id: 'start6', q: 'Do I need a lot of money?', a: 'No. The plan works on whatever lands, and the first run can be ₹100.', t: ['lot', 'much', 'enough', 'money', 'minimum', 'small'] },
    ] },
    { id: 'money', name: 'Your money', qa: [
      { id: 'money1', q: 'Where does my money go?', a: 'By UPI mandate to the fund house, which holds it in your name. Groww never holds it.', t: ['where', 'go', 'goes', 'held', 'hold', 'fund house'] },
      { id: 'money2', q: 'What if Groww shuts down?', a: 'Your money sits with the fund house, not with Groww. You can still get it back through the fund house.', t: ['shuts', 'shut', 'down', 'closes', 'bankrupt', 'groww'] },
      { id: 'money3', q: 'Can I lose it all?', a: 'Not in a broad-market fund. A bad year is about a 25% fall: {invest} becomes about {worst}. Going to zero would mean India’s fifty biggest companies all failed at once.', t: ['lose', 'loss', 'all', 'zero', 'fall', 'crash', 'market', 'worst'] },
      { id: 'money4', q: 'How do I get money back?', a: 'Stop the plan and ask for money back. It arrives in a few working days.', t: ['back', 'withdraw', 'get', 'return', 'out', 'stop'] },
      { id: 'money5', q: 'What if the app crashes while paying?', a: 'The mandate completes with the bank and the fund house. Money is never stuck in the app.', t: ['crashes', 'crash', 'app', 'paying', 'stuck', 'fails'] },
      { id: 'money6', q: 'Is this real money?', a: 'No. This is a prototype. Nothing moves.', t: ['real', 'prototype', 'demo', 'fake'] },
    ] },
    { id: 'fno', name: 'F&O and stocks', qa: [
      { id: 'fno1', q: 'What is F&O?', a: 'A bet on where a price will be by a date. If it goes the other way, the whole amount can go.', t: ['f&o', 'fno', 'options', 'futures', 'what is'] },
      { id: 'fno2', q: 'Why does F&O say Activate?', a: 'The regulator requires income proof for F&O. Most students do not have it.', t: ['activate', 'activation', 'income', 'proof'] },
      { id: 'fno3', q: 'How many people lose in F&O?', a: 'SEBI found 9 in 10 lose, about ₹1,20,000 a year on average (2024).', t: ['many', 'lose', 'sebi', 'people', 'percent'] },
      { id: 'fno4', q: 'Should I start with stocks?', a: 'Single companies swing more than a broad fund. Start with the fund; stocks stay open.', t: ['stocks', 'stock', 'shares', 'company', 'start with'] },
      { id: 'fno5', q: 'Can I still trade if I want to?', a: 'Yes. Nothing here is locked. The guide only tells you the odds.', t: ['trade', 'trading', 'still', 'allowed', 'locked'] },
    ] },
    { id: 'plan', name: 'Your plan', qa: [
      { id: 'plan1', q: 'What is a plan?', a: 'One sentence you set once: what stays untouched and what share of the rest goes in. It runs when money lands.', t: ['plan', 'rule', 'what is'] },
      { id: 'plan2', q: 'Why a floor?', a: 'So the money that has to be there every month is never touched.', t: ['floor', 'untouched', 'why floor'] },
      { id: 'plan3', q: 'Why a share and not a fixed amount?', a: 'Your income changes. A fixed amount breaks when it dips; a share just gets smaller.', t: ['share', 'percent', 'fixed', 'amount', 'sip', 'why share'] },
      { id: 'plan4', q: 'Why does it stop at 50%?', a: 'So at least half of what is left always stays with you.', t: ['50', 'fifty', 'half', 'max', 'limit', 'stop at'] },
      { id: 'plan5', q: 'What happens next time money lands?', a: '{floor} stays, {share} of the rest goes in, without you doing anything.', t: ['next', 'lands', 'happens', 'automatically', 'time'] },
      { id: 'plan6', q: 'What does First run: ₹100 only do?', a: 'Your first run puts in ₹100 at most, so you can watch it work. Every run after that uses your full share.', t: ['100', 'first run', 'cap', 'only'] },
      { id: 'plan7', q: 'Can I change it?', a: 'Yes, tap Change or stop on Home.', t: ['change', 'edit', 'cancel', 'modify', 'stop'] },
      { id: 'plan8', q: 'Which one am I if my stipend is sometimes late?', a: 'Irregular. The plan works on what actually arrives, not the date.', t: ['stipend', 'late', 'irregular', 'which', 'shape'] },
      { id: 'plan9', q: 'Does the amount need to be exact?', a: 'No. It only sets the first estimate; the plan recomputes on every real inflow.', t: ['exact', 'estimate', 'roughly', 'accurate'] },
      { id: 'plan10', q: 'What counts as untouched?', a: 'Whatever must be there every month: rent, food, money sent home, EMIs.', t: ['counts', 'untouched', 'rent', 'food', 'emi'] },
      { id: 'plan11', q: 'What if I put ₹0 as the floor?', a: 'Then the share applies to everything that came in. Allowed, but be sure.', t: ['zero floor', '0', 'nothing aside'] },
      { id: 'plan12', q: 'Why is it ₹0?', a: 'Your floor of {floor} is at or above the {lastInflow} that came in, so nothing is left this time.', t: ['why zero', 'why 0', 'nothing left', 'rounds'] },
    ] },
    { id: 'basics', name: 'The basics', qa: [
      { id: 'basics1', q: 'Why one fund?', a: 'Choosing between forty funds is where most first-timers stop. One broad fund is enough to start.', t: ['one fund', 'why one', 'choose', 'which fund', 'forty'] },
      { id: 'basics2', q: 'What does index mean?', a: 'A fixed list of India’s biggest companies. The fund just holds that list.', t: ['index', 'nifty', 'list', 'mean'] },
      { id: 'basics3', q: 'What about gold or small companies?', a: 'Both swing more. They are for later, after the plan has run a few times.', t: ['gold', 'small companies', 'small', 'later', 'other'] },
      { id: 'basics4', q: 'Is this the real Groww?', a: 'No. A case-study prototype with no real money.', t: ['real groww', 'official', 'affiliated'] },
      { id: 'basics5', q: 'How do I reset?', a: 'Tap Reset demo on the You tab.', t: ['reset', 'restart', 'clear'] },
    ] },
  ],
  chips: {
    '/welcome': ['start1', 'start2', 'start3'],
    '/': ['start1', 'start5', 'plan5', 'money1'],
    '/kyc': ['start2', 'start4', 'start3', 'fno2'],
    '/basics': ['basics2', 'money3', 'basics1'],
    '/rule/1': ['plan8', 'plan9', 'start6'],
    '/rule/2': ['plan10', 'plan11', 'plan2'],
    '/rule/3': ['plan3', 'plan4', 'plan12'],
    '/rule/4': ['money3', 'money5', 'money4', 'plan6'],
    '/invest': ['basics1', 'basics3', 'basics2'],
    '/stocks': ['fno4', 'fno5', 'basics1'],
    '/fno': ['fno1', 'fno2', 'fno3', 'fno5'],
    '/you': ['basics4', 'basics5', 'money6'],
  },
};
