export const BANNED = ['NAV', 'expense ratio', 'XIRR', 'AUM', 'folio', 'units', 'alpha', 'beta', 'large-cap', 'mid-cap', 'small-cap', 'equity', 'debt', 'ELSS', 'direct plan', 'regular plan', 'redemption', 'lock-in', 'KYC', 'demat'];

export const SCREEN = {
  welcome: {
    chip: 'Account created',
    title: 'Welcome to Groww, Nilay',
    body: 'Ask anything before you put in a rupee.',
    points: ['Nothing moves until you say so', 'Start with any amount from ₹100', 'Take your money out any time'],
    cta: 'Look around',
  },
  kyc: {
    title: 'Verify your account',
    sub: 'Needed once, by law, before any investment. Tap a row to see why.',
    ready: '{n} of 6 ready',
    rows: [
      { id: 'pan', name: 'PAN card', why: 'Tax rules require it for any investment account.', where: 'Most people have one. If not, apply on the income tax site; it takes about two days.' },
      { id: 'aadhaar', name: 'Aadhaar, with your own phone linked', why: 'The OTP goes to the phone linked to it.', where: 'If it is linked to a parent’s number, ask them to read out the OTP, or update the number at any Aadhaar centre.' },
      { id: 'bank', name: 'A bank account in your name', why: 'Money moves only to and from this account.', where: 'A joint account or a parent’s account will not work. A basic savings account is enough.' },
      { id: 'selfie', name: 'A selfie', why: 'A live check that you are you.', where: 'Taken in the app, in good light.' },
      { id: 'sign', name: 'Your signature', why: 'The regulator asks for a signature image.', where: 'Sign on plain paper and photograph it.' },
      { id: 'nominee', name: 'A nominee', why: 'Someone who gets the money if something happens to you.', where: 'Any family member’s name and date of birth.' },
    ],
    fno: { name: 'For F&O only: income proof', sub: 'Salary slip, bank statement or tax return', why: 'The regulator requires it. Most students do not have it, which is why F&O shows Activate.', where: 'Not needed for funds or stocks.' },
    cta: 'Submit documents',
    demo: 'Fill all for demo',
  },
  home: {
    title: 'Ask before you invest',
    sub: 'No question is too basic. Tap one.',
    askIds: ['start6', 'money3', 'money1', 'money4', 'start7'],
    all: 'See all questions',
    moneyTitle: 'Your money', invested: 'Invested',
    holdingSub: 'Held at the fund house in your name. Take it out any time; money back in a few working days.',
    out: 'Take money out', outDone: 'Money-back request placed. It arrives in a few working days.',
    onceDone: '{amt} invested. Nothing else moves unless you say so.',
    ruleDone: 'Rule set. It only runs when money lands, and you can stop it any time.',
    readyTitle: 'When you are ready',
    once: { title: 'Invest once', body: 'Any amount from ₹100, into one broad fund. Nothing to pick.', cta: 'Choose an amount', again: 'Invest again' },
    ruleOpt: { title: 'Set a rule', tag: 'Optional', body: 'For money that arrives at different times. Decide once what stays untouched.', cta: 'Set a rule' },
    help: { title: 'Help with your account', docs: 'Documents', docsBefore: '{n} of 6 ready. See what is needed and why.', docsAfter: 'Submitted. Checks finish within 24 working hours.', basics: 'The basics', basicsBody: 'Three short cards: funds, risk, falls.', basicsDone: 'Read. Open again any time.' },
    rule: {
      title: 'Your rule', active: 'Active', paused: 'Paused', landed: 'Money landed', run: 'Run the rule', landedLabel: 'How much landed?',
      pause: 'Pause', resume: 'Resume', change: 'Change', stop: 'Stop', next: 'Next time money lands, this runs by itself.',
      pausedNote: 'Paused. Money that lands stays in your bank.', received: 'Received', kept: 'Kept untouched', invested: 'Invested',
      stopped: 'Rule stopped. Nothing more goes in. Money already invested stays yours.',
    },
    askTitle: 'Ask before you invest', askSub: 'Plain answers, with your numbers.',
  },
  fund: { name: 'Nifty 50 Index Fund', meta: 'Index fund · India’s 50 biggest companies', badge: '50' },
  basics: {
    title: 'The basics',
    cards: [
      { title: 'What a mutual fund is', body: 'Your money joins thousands of other people’s money and buys a slice of many companies at once. One purchase, many companies. A fund house holds it in your name.' },
      { title: 'What risk means', body: 'Prices move every day. Risk is how far they can move against you, and for how long. A broad fund of big companies moves less than one company, and far less than a bet on a date.' },
      { title: 'What happens when markets fall', body: 'Falls come often. A bad year can be a 25% fall: ₹1,000 becomes about ₹750. In 2008 it was about half. Past recoveries promise nothing about the next one. Money you need soon should not be here.' },
    ],
    next: 'Next', done: 'Got it',
  },
  flow: 'Set a rule (optional)',
  once: {
    title: 'Invest once', label: 'How much would you like to start with?', chips: [100, 500, 1000],
    min: 'The smallest amount is ₹100.', outT: 'Taking it out', out: 'Any time. Money back takes a few working days.',
    cta: 'Invest {amt}', ctaDocs: 'Add documents to invest', docsNote: 'Groww needs your documents once before any money moves.',
  },
  rule1: { title: 'How does your money arrive?', shapes: [['regular', 'Regular', 'Same amount, on a date you know'], ['irregular', 'Irregular', 'Different amounts, no fixed date'], ['onetime', 'One-time', 'Came once, not coming again soon']], label: 'Roughly how much came in last time?', err: 'Pick one of the three and enter the amount, more than ₹0.', cta: 'Next' },
  rule2: { title: 'What has to stay untouched each month?', hint: 'Rent, food, money sent home, EMIs. A rough total is enough.', zero: '₹0 means nothing is kept aside. Fine if that is true.', over: 'That is more than the {L} that came in, so nothing is left to invest. You can still go on.', cta: 'Next' },
  rule3: { title: 'How much of what is left goes in?', line: '{share} of the {left} left after your floor.', half: 'Half is the most this rule takes, so half of what is left always stays with you.', youInvest: 'You invest', cta: 'Review' },
  rule4: {
    title: 'Review before you confirm',
    came: 'Money that came in', stays: 'Stays untouched', shareL: 'Share of the rest', goes: 'Goes in this time',
    fallT: 'If markets fall', crashT: 'If the app or payment stops mid-way', stopT: 'Changing or stopping',
    crash: 'Money goes by UPI mandate to the fund house, never to the app. A half-finished payment does not go through.',
    stop: 'Pause, change or stop it any time. Money back takes a few working days.',
    cta: 'Set this rule',
  },
  explore: {
    one: { title: 'One fund is enough to start', body: 'A broad-market index fund holds a slice of India’s biggest companies. Nothing to pick, nothing to time.', cta: 'Start my first investment', ctaRule: 'See my rule' },
    later: { title: 'Other options, for later', rows: [['Gold', 'Moves differently from companies. Useful after your rule has run a few times.'], ['Small companies', 'Bigger swings both ways. Not a first step.'], ['Government bonds', 'Steadier, slower. Fine for money you need within two years.']] },
  },
  mfTabs: [['/mf', 'First investment'], ['/mf/explore', 'Explore']],
  stocks: {
    gate: { title: 'Stocks come second', body: 'Single companies swing more than a broad fund. Your first fund is a better first step; stocks stay open.', open: 'Open Stocks', back: 'Go to my first investment' },
    index: [['NIFTY 50', '24,812.05', '+0.42%'], ['SENSEX', '81,104.30', '+0.38%']],
    watch: 'Nilay’s Watchlist',
    rows: [['HDFC Bank', '₹1,642.10', '+0.8%'], ['ITC', '₹412.35', '-0.3%'], ['Tata Steel', '₹151.20', '+1.4%'], ['Canara Bank', '₹108.40', '+1.2%'], ['PNB', '₹104.75', '-0.6%']],
    note: 'Prototype: illustrative prices, not live.',
  },
  fno: {
    gate: { title: 'Read this first', body: 'F&O is a bet on where a price will be by a date. If it goes the other way, the whole amount can go. SEBI found about 9 in 10 individual F&O traders lost money (2024 study). Activation needs income proof.', open: 'I understand, open F&O', ask: 'Ask before you trade F&O' },
    activate: 'Activate (income proof needed)',
    section: 'Most bought options',
    rows: [['NIFTY 22 Sep 23600 Call', '₹142.50'], ['NIFTY 22 Sep 23500 Call', '₹188.20'], ['SENSEX 17 Sep 74000 Put', '₹96.40'], ['SENSEX 17 Sep 75000 Call', '₹121.90'], ['Crude Oil Mini', '₹5,812']],
    note: 'Prototype: illustrative prices, not live.',
  },
  pay: { title: 'Pay', body: 'Out of scope for this prototype. The first investment lives in Mutual Funds.' },
  you: { title: 'Profile', name: 'Nilay', line: 'Prototype for a case study. Not affiliated with Groww.', mode: 'First Investment mode', modeNote: 'Shown to new accounts until the first rule is set.', account: 'Account', accountBefore: 'Documents needed', accountAfter: 'Submitted, verifying', reset: 'Reset demo' },
  tabs: [['/stocks', 'Stocks', 'stocks'], ['/fno', 'F&O', 'fno'], ['/mf', 'Mutual Funds', 'mf'], ['/pay', 'Pay', 'pay']],
};

export const GUIDE = {
  name: 'Ask before you invest',
  more: 'More topics',
  opening: {
    '/welcome': 'You’re in. Ask me what happens next.',
    '/mf': 'Three steps. Ask me about any of them.',
    '/mf/explore': 'One fund is enough to start. Ask me why.',
    '/kyc': 'Six things. Ask me about any row.',
    '/basics': 'Three cards. Ask me if any of them is unclear.',
    '/rule/1': 'Pick the shape that fits most months.',
    '/rule/2': 'This is the number the rule never touches.',
    '/rule/3': 'Slide it. The rupee figure updates as you go.',
    '/rule/4': 'Last step. Ask me the scary questions.',
    '/once': 'Any amount from ₹100. Ask me anything first.',
    '/stocks': 'Stocks stay open. Ask me why they come second.',
    '/fno': 'Read the red card first, then ask me anything.',
    '/pay': 'Pay is outside this prototype.',
    '/you': 'Prototype settings. Ask me what resets.',
  },
  topics: [
    { id: 'start', name: 'Start here', qa: [
      { id: 'start1', q: 'How do I start?', a: 'Ask anything first. When you are ready, invest once from ₹100 or set a rule. Documents are needed once before money moves.' },
      { id: 'start2', q: 'What documents do I need?', a: 'PAN, Aadhaar with your phone linked, a bank account in your name, a selfie, a signature photo and a nominee. The documents list explains each.' },
      { id: 'start3', q: 'How long does it take?', a: 'Documents take about 10 minutes if you have them. Groww then checks them within 24 working hours.' },
      { id: 'start4', q: 'The OTP went to my dad’s phone.', a: 'Aadhaar sends it to the number linked at enrolment. Ask them to read it out, or update the number at any Aadhaar centre.' },
      { id: 'start5', q: 'Why does it say verifying?', a: 'A person or a system checks your documents. Nothing moves until that is done. Look around meanwhile.' },
      { id: 'start7', q: 'Do I have to set a rule?', a: 'Not at all. Invest once whenever you like. A rule is only for people whose money arrives at different times.' },
      { id: 'start6', q: 'Do I need a lot of money?', a: 'You do not need a lot. You can start with ₹100 and add more only when you want to.' },
    ] },
    { id: 'money', name: 'Your money', qa: [
      { id: 'money1', q: 'Where does my money go?', a: 'By UPI mandate to the fund house, which holds it in your name. Groww never holds it.' },
      { id: 'money2', q: 'What if Groww shuts down?', a: 'Your money sits with the fund house, not with Groww. You can still get it back through the fund house.' },
      { id: 'money3', q: 'Can I lose money?', a: 'Yes, for a while. A bad year can turn {invest} into about {worst}; in 2008 markets fell about half. Losing all of it would need India’s fifty biggest companies to fail together.' },
      { id: 'money4', q: 'How do I get money back?', a: 'Tap Take money out under Your money. It arrives in a few working days.' },
      { id: 'money5', q: 'What if the app crashes while paying?', a: 'The mandate completes with the bank and the fund house, or it does not go through. Money is never stuck in the app.' },
      { id: 'money6', q: 'Is this real money?', a: 'No. This is a prototype. Nothing moves.' },
    ] },
    { id: 'fno', name: 'F&O and stocks', qa: [
      { id: 'fno1', q: 'What is F&O?', a: 'A bet on where a price will be by a date. If it goes the other way, the whole amount can go.' },
      { id: 'fno2', q: 'Why does F&O say Activate?', a: 'The regulator requires income proof for F&O. Most students do not have it.' },
      { id: 'fno3', q: 'How many people lose in F&O?', a: 'SEBI found about 9 in 10 individual F&O traders lost money (2024 study).' },
      { id: 'fno4', q: 'Should I start with stocks?', a: 'Single companies swing more than a broad fund. Start with the fund; stocks stay open.' },
      { id: 'fno5', q: 'Can I still trade if I want to?', a: 'Yes. Nothing here is locked. The warning only tells you the odds.' },
    ] },
    { id: 'plan', name: 'Your rule', qa: [
      { id: 'plan1', q: 'What is a rule?', a: 'One sentence you set once: what stays untouched and what share of the rest goes in. It runs when money lands.' },
      { id: 'plan2', q: 'Why a floor?', a: 'So the money that has to be there every month is never touched.' },
      { id: 'plan3', q: 'Why a share and not a fixed amount?', a: 'Your income changes. A fixed amount breaks when it dips; a share just gets smaller.' },
      { id: 'plan4', q: 'Why does it stop at 50%?', a: 'So at least half of what is left always stays with you.' },
      { id: 'plan5', q: 'What happens next time money lands?', a: '{floor} stays, {share} of the rest goes in, without you doing anything.' },
      { id: 'plan7', q: 'Can I change or stop it?', a: 'Yes. Pause, Change and Stop sit on your rule card. The rule is optional anyway.' },
      { id: 'plan8', q: 'Which one am I if my stipend is sometimes late?', a: 'Irregular. The rule works on what actually arrives, not the date.' },
      { id: 'plan9', q: 'Does the amount need to be exact?', a: 'No. It only sets the first estimate; the rule recomputes on every real inflow.' },
      { id: 'plan10', q: 'What counts as untouched?', a: 'Whatever must be there every month: rent, food, money sent home, EMIs.' },
      { id: 'plan11', q: 'What if I put ₹0 as the floor?', a: 'Then the share applies to everything that came in. Allowed, but be sure.' },
      { id: 'plan12', q: 'Why is it ₹0?', a: 'Your floor of {floor} is at or above the {lastInflow} that came in, so nothing is left this time.' },
    ] },
    { id: 'basics', name: 'The basics', qa: [
      { id: 'basics1', q: 'Why one fund?', a: 'Choosing between forty funds is where most first-timers stop. One broad fund is enough to start.' },
      { id: 'basics2', q: 'What does index mean?', a: 'A fixed list of India’s biggest companies. The fund just holds that list.' },
      { id: 'basics3', q: 'What about gold or small companies?', a: 'Both swing more. They are for later, after the rule has run a few times.' },
      { id: 'basics4', q: 'Is this the real Groww?', a: 'No. A case-study prototype with no real money.' },
      { id: 'basics5', q: 'How do I reset?', a: 'Tap your profile circle, then Reset demo.' },
    ] },
  ],
  chips: {
    '/welcome': ['start1', 'start2', 'start3'],
    '/mf': ['start1', 'start7', 'money2', 'basics1'],
    '/mf/explore': ['basics1', 'basics3', 'basics2'],
    '/kyc': ['start2', 'start4', 'start3', 'fno2'],
    '/basics': ['basics2', 'money3', 'basics1'],
    '/rule/1': ['plan8', 'plan9', 'start6'],
    '/rule/2': ['plan10', 'plan11', 'plan2'],
    '/rule/3': ['plan3', 'plan4', 'plan12'],
    '/rule/4': ['money3', 'money5', 'plan7', 'money4'],
    '/once': ['start6', 'money3', 'money4', 'money5'],
    '/stocks': ['fno4', 'fno5', 'basics1'],
    '/fno': ['fno1', 'fno2', 'fno3', 'fno5'],
    '/pay': ['basics4', 'start1', 'money1'],
    '/you': ['basics4', 'basics5', 'money6'],
  },
};
